# Generated by Django 5.2 on 2025-05-05 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('performance', 'Performance Insight'), ('learning', 'Learning Recommendation'), ('lead', 'Lead Suggestion'), ('sales', 'Sales Tip')], default='performance', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_source', models.CharField(choices=[('manual', 'Manually Added'), ('ai_suggested', 'AI Suggested'), ('referral', 'Referral'), ('campaign', 'Campaign')], default='manual', max_length=20)),
                ('interest', models.CharField(choices=[('insurance', 'Insurance'), ('credit_card', 'Credit Card'), ('loan', 'Loan'), ('savings', 'Savings Account'), ('demat', 'Demat Account'), ('investment', 'Investment'), ('multiple', 'Multiple Products'), ('undecided', 'Undecided')], default='undecided', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('priority_score', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('product', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_type', models.CharField(choices=[('new', 'New Customer'), ('existing', 'Existing Customer'), ('referred', 'Referred Customer')], default='new', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(choices=[('insurance', 'Insurance'), ('credit_card', 'Credit Card'), ('loan', 'Loan'), ('savings', 'Savings Account'), ('demat', 'Demat Account'), ('investment', 'Investment')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lead_source', models.CharField(choices=[('direct', 'Direct Contact'), ('referral', 'Referral'), ('ai_suggested', 'AI Suggested'), ('campaign', 'Campaign'), ('other', 'Other')], default='direct', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_customers', models.IntegerField(default=0)),
                ('insurance_target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_card_target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('investment_target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
